### ISSUE TITLE
How to set fsgroup in pod template?

### ISSUE THREAD

**Issue by mrceresa** [carlossg/jenkins-kubernetes-plugin#10]
Dear Carlos,
thanks for your continued support on this. 
I tried to understand how to pass the securityContext/fsgroup with Jenkins uid in order to fix 
https://github.com/jenkinsci/docker-jnlp-slave/issues/15

but I'm not sure: should I modify the code/resources of the plugin or is there an option of the pod template where I can put it on? 

Thanks and regards,

Mario

**Comment by carlossg** [comment]
There is no option to set it, PRs welcome

BTW the correct repo location is https://github.com/jenkinsci/kubernetes-plugin
