### ISSUE TITLE
Total container cap Reached message, even when only few pods active

### ISSUE THREAD

**Issue by alamsz** [carlossg/jenkins-kubernetes-plugin#11]
I am experiencing weird issue with the kubernetes plugin. 
<img width="694" alt="screen shot 2016-11-21 at 8 59 29 pm" src="https://cloud.githubusercontent.com/assets/1900931/20485301/7e6483ec-b02d-11e6-9040-5ed7a0f02edc.png">

The log stated that I have reached number of pods running, even when there is only 6 pods jenkins slave running
<img width="422" alt="screen shot 2016-11-21 at 9 01 14 pm" src="https://cloud.githubusercontent.com/assets/1900931/20485350/b2c10a5c-b02d-11e6-9867-ef383273f88a.png">

My setup as follows
One provider 
10 pod templates

Currently what I do as workaround to this problem is to increase container cap value, so that my job could run, but this will be too bothersome

Is there a way to reset this container cap? or is there any workaround for this beside increasing container cap number

**Comment by carlossg** [comment]
you need to check the stopped ones too `kubectl get pods -a`

**Comment by alamsz** [comment]
ah ok, there are a bunch of pods with status Error, and not cleaned up by the plugin, is there any way to make the Error pod removed itself instead of deleting them manually

**Comment by carlossg** [comment]
no, because you need to check what the error is and fix it to prevent infinite scheduling of pods

BTW the correct repo location is https://github.com/jenkinsci/kubernetes-plugin
