### ISSUE TITLE
Docker run hangs at setting agent port for JNLP

### ISSUE THREAD

**Issue by Kielan** [carlossg/jenkins-kubernetes-plugin#3]
the command

docker run --rm --name jenkins -p 8080:8080 -p 50000:50000 -v /var/jenkins_home csanchez/jenkins-kubernetes

hangs indefinitely when setting agent port for jnlp

I've used this repo as the main has their issues on github closed.

**Comment by carlossg** [comment]
What do you men hangs? it is the last log entry
See https://github.com/jenkinsci/docker/issues/126

**Comment by carlossg** [comment]
and this is the repo for the jenkins-kubernetes plugin, not for the jenkins docker image
