### ISSUE TITLE
Make it possible to authenticate using tokens

### ISSUE THREAD

**Issue by thesamet** [carlossg/jenkins-kubernetes-plugin#4]
Currently the plugin allows to authenticate to an api server using username/password pairs. It would be nice to be able to use token based authentication as well.

**Comment by liggitt** [comment]
+1, especially since basic auth is not considered best practice for the API, and will be strongly discouraged in the future

**Comment by mfojtik** [comment]
+1 it will also make this plugin usable for OpenShift (as OpenShift support just bearer token auth).

**Comment by carlossg** [comment]
the repo is moved to https://github.com/jenkinsci/kubernetes-plugin 

it has been implemented there https://github.com/jenkinsci/kubernetes-plugin/commit/021487eb5f835ea1c0eb7d55be4122f5a132efcb

**Comment by liggitt** [comment]
great, thanks
